owner: indicima
repo: vitals.indicima.ca

sites:
  - name: Indicima.com
    url: https://indicima.ca
  - name: Indicima® Vitals™
    url: https://vitals.indicima.ca
  - name: Indicima® Swift™
    check: "tcp-ping"
    url: swift.indicima.ca
    port: 993
  - name: Vitals User
    url: $IVC6d7945e2f00aa5093dd1f2d25dc19421

status-website:
  cname: vitals.indicima.ca
  logoUrl: https://indicima.ca/wp-content/uploads/2022/09/logo-multi-medium.png
  name: Indicima Vitals
  introTitle: "Indicima Vitals"
  introMessage: Uptime Monitoring
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  footer: .
